import type { AiCareerReviewLegacy, AiCareerReviewPayload } from '@enrich-skills/shared';
import { isIndustryCareerReport } from '@enrich-skills/shared';

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function p(text: string): string {
  return `<p style="margin:0 0 12px;line-height:1.55;font-size:15px">${esc(text)}</p>`;
}

function h2(text: string): string {
  return `<h2 style="margin:24px 0 10px;font-size:18px;color:#1e293b">${esc(text)}</h2>`;
}

function ul(items: string[]): string {
  if (items.length === 0) return '';
  return `<ul style="margin:0 0 12px;padding-left:20px;font-size:15px;line-height:1.5">${items
    .map((i) => `<li>${esc(i)}</li>`)
    .join('')}</ul>`;
}

function buildV2Html(studentName: string, report: AiCareerReviewPayload): string {
  const scores = [
    ['Logic', report.competencyScores.logic],
    ['Code quality', report.competencyScores.codeQuality],
    ['Speed', report.competencyScores.speed],
    ['Language versatility', report.competencyScores.languageVersatility],
  ] as const;

  const scoreRows = scores
    .map(
      ([label, value]) =>
        `<tr><td style="padding:6px 12px 6px 0">${esc(label)}</td><td style="padding:6px 0;font-weight:600">${value}/10</td></tr>`
    )
    .join('');

  const langBadges = report.languageAgility.languageProficiency
    .map((lp) => `${lp.language}: ${lp.proficiencyLevel} (${lp.fluencyScore}/10)`)
    .join(' · ');

  const roles = report.industryFitment.roleMappings
    .map((r) => `<li><strong>${esc(r.role)}</strong> [${esc(r.fitLevel)}] — ${esc(r.rationale)}</li>`)
    .join('');

  const roadmap = report.fourWeekRoadmap
    .slice()
    .sort((a, b) => a.week - b.week)
    .map(
      (w) =>
        `<div style="margin-bottom:12px"><strong>Week ${w.week}: ${esc(w.focus)}</strong>${ul(w.tasks)}</div>`
    )
    .join('');

  return `
    <div style="font-family:system-ui,-apple-system,sans-serif;color:#334155;max-width:640px">
      <h1 style="margin:0 0 8px;font-size:22px;color:#0f172a">Career comparison report</h1>
      <p style="margin:0 0 20px;font-size:15px;color:#64748b">Prepared for <strong>${esc(studentName)}</strong></p>
      ${p(report.executiveSummary)}
      ${h2('Executive competency snapshot')}
      <table style="border-collapse:collapse;margin-bottom:16px;font-size:15px">${scoreRows}</table>
      ${h2('Language agility')}
      ${p(`Versatility ${report.languageAgility.versatilityScore}/10 — ${report.languageAgility.versatilityJustification}`)}
      ${p(langBadges)}
      ${h2('Production code quality')}
      ${p(report.codeQuality.readabilityAndMaintainability)}
      ${h2('Industry fitment')}
      <p style="margin:0 0 12px;padding:10px 14px;background:#dcfce7;border-radius:6px;font-weight:600;font-size:15px">${esc(report.industryFitment.employabilityTag)}</p>
      <ul style="margin:0 0 12px;padding-left:20px;font-size:15px">${roles}</ul>
      ${p(report.industryFitment.skillGapAnalysis)}
      ${h2('4-week skill gap roadmap')}
      ${roadmap}
      <p style="margin:24px 0 0;font-size:13px;color:#94a3b8">Generated by RankerShip · Vihaan Digital Solutions</p>
    </div>
  `;
}

function buildLegacyHtml(studentName: string, report: AiCareerReviewLegacy): string {
  return `
    <div style="font-family:system-ui,-apple-system,sans-serif;color:#334155;max-width:640px">
      <h1 style="margin:0 0 8px;font-size:22px;color:#0f172a">Career comparison report</h1>
      <p style="margin:0 0 20px;font-size:15px;color:#64748b">Prepared for <strong>${esc(studentName)}</strong></p>
      ${p(report.overallSummary)}
      ${h2('Strengths')}
      ${ul(report.strengths)}
      ${h2('Weaknesses')}
      ${ul(report.weaknesses)}
      ${h2('Recommendations')}
      ${ul(report.recommendations)}
      <p style="margin:24px 0 0;font-size:13px;color:#94a3b8">Generated by RankerShip · Vihaan Digital Solutions</p>
    </div>
  `;
}

export function buildCareerReportEmailHtml(
  studentName: string,
  report: AiCareerReviewPayload | AiCareerReviewLegacy
): string {
  if (isIndustryCareerReport(report)) return buildV2Html(studentName, report);
  return buildLegacyHtml(studentName, report);
}
